version: '3.8'

services:
  regwatch-ai:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE=http://localhost:3001/api/
      - DATABASE_URL=./data/database.sqlite
    volumes:
      - regwatch_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: PostgreSQL database for production
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: regwatch_ai
      POSTGRES_USER: regwatch
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    profiles:
      - postgres

  # Optional: Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    profiles:
      - redis

volumes:
  regwatch_data:
  postgres_data:
